from abc import ABC, abstractmethod
from app.models.provider import ProviderHealth

class MarketProvider(ABC):
    @abstractmethod
    async def start(self) -> None: ...
    @abstractmethod
    async def stop(self) -> None: ...
    @abstractmethod
    async def subscribe(self, symbols: list[str]) -> None: ...
    @abstractmethod
    async def unsubscribe(self, symbols: list[str]) -> None: ...
    @property
    @abstractmethod
    def health(self) -> ProviderHealth: ...
